namespace SettingsBinder.Generator.Generators;

[Generator]
public class SettingsSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var settingsClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSettingClass(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value)
            .Collect();

        context.RegisterSourceOutput(settingsClasses, Generate);
    }

    private static (string Namespace, string ClassName)? GetSettingClass(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classSyntax)
            return null;

        foreach (var attrList in classSyntax.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                var symbol = context.SemanticModel.GetSymbolInfo(attr).Symbol;
                if (symbol is IMethodSymbol methodSymbol)
                {
                    var attrName = methodSymbol.ContainingType.ToDisplayString();

                    // Match [Settings] or fully-qualified SettingsAttribute
                    if (attrName.EndsWith(".SettingsAttribute") || attrName.EndsWith(".Settings"))
                    {
                        if (context.SemanticModel.GetDeclaredSymbol(classSyntax) is INamedTypeSymbol classSymbol)
                        {
                            return (
                                Namespace: classSymbol.ContainingNamespace.ToDisplayString(),
                                ClassName: classSymbol.Name
                            );
                        }
                    }
                }
            }
        }

        return null;
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<(string Namespace, string ClassName)> settingsTypes)
    {
        // 1. Interface (once)
        context.AddSource("ISettings.g.cs", SourceText.From(GenerateISettingsInterface(), Encoding.UTF8));

        // 2. Per-class partials
        foreach (var (ns, className) in settingsTypes)
        {
            var partial = GeneratePartialSettingsClass(ns, className);
            context.AddSource($"{className}.Settings.g.cs", SourceText.From(partial, Encoding.UTF8));
        }

        // 3. Global binding extension method
        var binder = GenerateGlobalBindingRegistration(settingsTypes);
        context.AddSource($"SettingsConfigurationExtensions.g.cs", SourceText.From(binder, Encoding.UTF8));
    }

    private static string GenerateISettingsInterface() => """
        // <auto-generated/>
        namespace Api.Core.Settings;

        public interface ISettings
        {
            static abstract string SettingsSection { get; }
        }
        """;

    private static string GeneratePartialSettingsClass(string ns, string className) => $$"""
        // <auto-generated/>
        using Api.Core.Settings;

        namespace {{ns}};

        public sealed partial class {{className}} : ISettings
        {
            public static string SettingsSection => "{{className}}";
        }
        """;

    private static string GenerateGlobalBindingRegistration(IEnumerable<(string Namespace, string ClassName)> settingsTypes) => $$"""
          // <auto-generated/>
          using Microsoft.Extensions.Configuration;
          using Microsoft.Extensions.DependencyInjection;

          namespace Api.Core.Settings;

          public static class SettingsBinderExtensions
          {
              public static IServiceCollection AddSettingsOptions(this IServiceCollection services, IConfiguration configuration)
              {
          {{string.Join("\n", settingsTypes.Select(s =>
              $"            services.Configure<{s.Namespace}.{s.ClassName}>(configuration.GetSection({s.Namespace}.{s.ClassName}.SettingsSection));"))}}
          
                  return services;
              }
          }
          """;
}
