namespace SettingsBinder.Generator.Generators.Attributes;

[Generator]
public class AttributeGenerator  : IIncrementalGenerator
{
    private const string Namespace = $"{Constance.NamespaceBase}.Attributes";
    
    private const string SettingsAttributeSourceCode = $@"// <auto-generated/>
namespace {Namespace};

[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
public sealed partial class SettingsAttribute : System.Attribute;";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"SettingsAttribute.g.cs",
            SourceText.From(SettingsAttributeSourceCode, Encoding.UTF8)));
    }
}