
namespace TomRR.SourceGenerator.SettingsBinder;

[Generator]
public class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"SettingsAttribute.g.cs",
            SourceText.From(SettingsAttributeSourceCode, Encoding.UTF8)));
        
        var settingsClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSettingClass(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value)
            .Collect();

        context.RegisterSourceOutput(settingsClasses, Generate);
        

    }

    private static (string Namespace, string ClassName, string SectionName)? GetSettingClass(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classSyntax)
            return null;

        foreach (var attrList in classSyntax.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                var symbol = context.SemanticModel.GetSymbolInfo(attr).Symbol;
                if (symbol is IMethodSymbol methodSymbol)
                {
                    var attrName = methodSymbol.ContainingType.ToDisplayString();

                    // Match [Settings] or fully-qualified SettingsAttribute
                    if (attrName.EndsWith(".SettingsAttribute") || attrName.EndsWith(".Settings"))
                    {
                        if (context.SemanticModel.GetDeclaredSymbol(classSyntax) is INamedTypeSymbol classSymbol)
                        {
                            var sectionName = classSymbol.Name;

                            // Check constructor argument for override
                            if (attr.ArgumentList?.Arguments.Count > 0)
                            {
                                var constValue = context.SemanticModel.GetConstantValue(attr.ArgumentList.Arguments[0].Expression);
                                if (constValue.HasValue && constValue.Value is string str)
                                {
                                    sectionName = str;
                                }
                            }
                            
                            return (
                                Namespace: classSymbol.ContainingNamespace.ToDisplayString(),
                                ClassName: classSymbol.Name,
                                SectionName: sectionName
                            );
                        }
                    }
                }
            }
        }

        return null;
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<(string Namespace, string ClassName, string SectionName)> settingsTypes)
    {
        // 1. Interface (once)
        context.AddSource("ISettings.Settings.g.cs", SourceText.From(GenerateISettingsInterface(), Encoding.UTF8));

        // 2. Per-class partials
        foreach (var (ns, className, sectionName) in settingsTypes)
        {
            var partial = GeneratePartialSettingsClass(ns, className, sectionName);
            context.AddSource($"{className}.Settings.g.cs", SourceText.From(partial, Encoding.UTF8));
        }

        // 3. Global binding extension method
        var binder = GenerateGlobalBindingRegistration(settingsTypes);
        context.AddSource($"SettingsBinder.ServiceExtensions.g.cs", SourceText.From(binder, Encoding.UTF8));
    }

    private static string GenerateISettingsInterface() => $$"""
                                                            // <auto-generated/>
                                                            namespace {{Constance.NamespaceBase}};

                                                            public interface ISettings
                                                            {
                                                                static abstract string SectionName { get; }
                                                            }
                                                            """;

    private static string GeneratePartialSettingsClass(string ns, string className, string sectionName) => $$"""
          // <auto-generated/>
          using {{Constance.NamespaceBase}};

          namespace {{ns}};

          public sealed partial class {{className}} : ISettings
          {
              public static string SectionName => "{{sectionName}}";
          }
          """;

    private static string GenerateGlobalBindingRegistration(IEnumerable<(string Namespace, string ClassName, string SectionName)> settingsTypes) => $$$"""
          // <auto-generated/>
          using Microsoft.Extensions.Configuration;
          using Microsoft.Extensions.DependencyInjection;

          namespace {{{Constance.NamespaceBase}}};

          public static class SettingsBinderExtensions
          {
              public static IConfigurationBuilder AddConfigurationSources(IConfigurationBuilder builder)
              {
                  builder
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                    .AddJsonFile("appsettings.Development.json", optional: true, reloadOnChange: true)
                    .AddEnvironmentVariables();
                  
                  return builder;
              }
              
              public static WebApplicationBuilder AddSettingsOptions(this WebApplicationBuilder builder)
              {
          {{{string.Join("", settingsTypes.Select(s =>
              $"    {GetOptionBinding(s.Namespace, s.ClassName)}\n"))}}}        return builder;
              }
          }
          """;
    
    private static string GetOptionBinding(string @namespace, string className) => $$"""
              builder.Services
                    .AddOptions<global::{{@namespace}}.{{className}}>()
                    .Bind(builder.Configuration.GetSection(global::{{@namespace}}.{{className}}.SectionName))
                    .ValidateDataAnnotations()
                    .ValidateOnStart();
                    
          """;
    
    private const string SettingsAttributeSourceCode = $@"//<auto-generated/>
#nullable enable

namespace {Constance.NamespaceBase};

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public sealed partial class SettingsAttribute : System.Attribute
{{
    public string? SectionName {{ get; }}

    public SettingsAttribute() {{ }}

    public SettingsAttribute(string sectionName)
    {{
        SectionName = sectionName;
    }}
}}";
}