using System.IO;

namespace TomRR.SourceGenerator.SettingsBinder;

public static class DefaultConfigurationExtension
{
    public const string SourceCode = $@"//<auto-generated/>
#nullable enable
using Microsoft.Extensions.Configuration;
using System.IO;

namespace {Constance.NamespaceBase};

/// <summary>
/// Provides a default configuration pipeline suitable for most applications.
/// </summary>
public static class ConfigurationBuilderDefaultsExtensions
{{
    /// <summary>
    /// Adds a pre-configured default configuration pipeline including base path, JSON files, user secrets, and environment variables.
    /// </summary>
    public static IConfigurationBuilder AddDefaultConfigurationSources<T>(this IConfigurationBuilder builder) where T : class 
        => builder
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile(""appsettings.json"", optional: false, reloadOnChange: true)
            .AddJsonFile(""appsettings.Development.json"", optional: true, reloadOnChange: true)
            .AddUserSecrets<T>()
            .AddEnvironmentVariables();
}}";
}