namespace TomRR.SourceGenerator.SettingsBinder.SourceCode;

public static class SettingsInterfaceExtension
{
    public static string SourceCode => $$"""
                                                            // <auto-generated/>
                                                            namespace {{Constance.NamespaceBase}};

                                                            /// <summary>
                                                            /// Marker interface for settings classes. Each implementing class must provide its configuration section name.
                                                            /// </summary>
                                                            public interface ISettings
                                                            {
                                                                /// <summary>
                                                                /// Gets the section name in the configuration from which this settings class should be bound.
                                                                /// This is generated automatically and can be overridden using the [Settings] attribute.
                                                                /// </summary>
                                                                static abstract string SectionName { get; }
                                                            }
                                                            """;
}