namespace TomRR.SourceGenerator.SettingsBinder.SourceCode;

public static class SettingsAttributeExtension
{
    public const string SourceCode = $@"//<auto-generated/>
#nullable enable

namespace {Constance.NamespaceBase};

/// <summary>
/// Attribute used to mark classes as configuration settings.
/// Enables source generation of configuration binding boilerplate.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public sealed partial class SettingsAttribute : System.Attribute
{{
    /// <summary>
    /// Optional section name override. If not provided, the class name will be used as the section name.
    /// </summary>
    public string? SectionName {{ get; }}

    /// <summary>
    /// Initializes a new instance of the <see cref=""""SettingsAttribute""""/> without a section name override.
    /// </summary>
    public SettingsAttribute() {{ }}

    /// <summary>
    /// Initializes a new instance of the <see cref=""SettingsAttribute""/> class with a custom section name.
    /// </summary>
    /// <param name=""sectionName"">The name of the configuration section this settings class binds to.</param>
    public SettingsAttribute(string sectionName)
    {{
        SectionName = sectionName;
    }}
}}";
}