namespace TomRR.SourceGenerator.SettingsBinder.SourceCode;

public class SettingsPocoExtension
{
    public static string SourceCode(string ns, string className, string sectionName) => $$"""
          // <auto-generated/>
          using {{Constance.NamespaceBase}};

          namespace {{ns}};

          /// <summary>
          /// Partial settings class generated for configuration binding.
          /// Implements <see cref="ISettings"/> with a static section name.
          /// </summary>
          public sealed partial class {{className}} : ISettings
          {
                
              /// <inheritdoc/>
              public static string SectionName => "{{sectionName}}";
          }
          """;
}